# config context path to "/" by setting an empty string
server:
  contextPath:

cloud:
  aws:
    credentials:
      accessKey: AKIAJYL3KISVYWOSOFRA
      secretKey: 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
      region: eu-west-1
    s3:
      bucket: pzprojektbucket